spring:
  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/loja
    username: lojaapp
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver